tap "nikitabobko/tap"
tap "common-fate/granted"

# Base CLI
brew "git"
brew "stow"
brew "mise"
brew "direnv"
brew "tmux"
brew "neovim"
brew "coreutils"
brew "wget"
brew "awscli@2"
brew "devcontainer"
brew "btop"
brew "git-crypt"
brew "gpg"
brew "telnet"
brew "plantuml"
brew "granted"

# GUI (macOS)
cask "ui"
cask "visual-studio-code"
cask "istat-menus"
cask "telegram"
cask "daisydisk"
cask "forklift"
cask "transmission"
cask "google-chrome"
cask "raycast"
cask "yandex-music"
cask "charles"
cask "postman"
cask "the-unarchiver"
cask "google-drive"
cask "1password"
cask "slack"
cask "windows-app"
cask "tableplus"
cask "medis"
cask "orbstack"
cask "chatgpt"
cask "ledger-live"
cask "zed@preview"
cask "iina"
cask "aerospace"
cask "session-manager-plugin"
cask "wezterm@nightly"
cask "1password-cli"

# Fonts
cask "font-symbols-only-nerd-font"
cask "font-jetbrains-mono"
cask "font-maple-mono"
cask "font-ubuntu-mono"
cask "font-lilex"

# Mac App Store helper (optional)
brew "mas"
