# tap "nikitabobko/tap"
tap "common-fate/granted"

# Base CLI
brew "git"
brew "stow"
brew "mise"
brew "tmux"
brew "neovim"
brew "coreutils"
brew "wget"
brew "awscli@2"
brew "devcontainer"
brew "btop"
brew "git-crypt"
brew "gpg"
brew "telnet"
brew "plantuml"
brew "granted"
brew "cocoapods"

# PostgreSQL tools
brew "libpq"

# Ruby dependencies
brew "libyaml"
brew "gmp"

# GUI (macOS)
cask "unifi-identity-enterprise"
cask "visual-studio-code"
cask "telegram"
cask "daisydisk"
cask "forklift"
cask "google-chrome"
cask "raycast"
cask "yandex-music"
cask "charles"
cask "postman"
cask "the-unarchiver"
# cask "google-drive"
cask "1password"
cask "slack"
cask "tableplus"
cask "medis"
cask "orbstack"
cask "chatgpt"
cask "session-manager-plugin"
cask "ghostty"
cask "1password-cli"
cask "ollama"
cask "zen"
cask "tailscale"

# Fonts
cask "font-symbols-only-nerd-font"
cask "font-jetbrains-mono"
cask "font-maple-mono"
cask "font-ubuntu-mono"
cask "font-lilex"
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"

# Mac App Store helper (optional)
brew "mas"
