min_version = "2026.8.3"

[bootstrap.repos]
"~/.local/share/zinit/zinit.git" = { url = "https://github.com/zdharma-continuum/zinit.git", ref = "main" }
"~/.tmux/plugins/tpm" = { url = "https://github.com/tmux-plugins/tpm.git", ref = "master" }

[dotfiles]
"~/.config" = { source = "dotfiles/.config", mode = "symlink-each", exclude = ["btop/btop.conf"] }
"~/.config/btop/btop.conf" = { source = "dotfiles/.config/btop/btop.conf", mode = "copy" }
"~/.config/mise/miserc.toml" = { source = "profiles/mise/miserc.toml", mode = "template" }
"~/.local/bin" = { source = "dotfiles/.local/bin", mode = "symlink-each" }
"~/.local/share/theme" = { source = "dotfiles/.local/share/theme", mode = "symlink" }
"~/.zshrc" = { source = "dotfiles/.zshrc", mode = "symlink" }
