# Global tool versions managed by mise

[tools]
node = "lts"
# ruby = "3"
# python = "3.12"
# go = "1.22"
fzf = "latest"
ripgrep = "latest"
jq = "latest"
neovim = "latest"
bat = "latest"
eza = "latest"
lazygit = "latest"
delta = "latest"
starship = "latest"
