# Global tool versions managed by mise
[alias]
tpm = "https://github.com/svyatogor/asdf-tpm"

[tools]
node = "lts"
# ruby = "3"
# python = "3.12"
# go = "1.22"
fzf = "latest"
ripgrep = "latest"
jq = "latest"
neovim = "latest"
bat = "latest"
eza = "latest"
lazygit = "latest"
delta = "latest"
starship = "latest"
tpm = "latest"
"ubi:openai/codex" = { version = "latest", exe = "codex-aarch64-apple-darwin", rename_exe = "codex" }
"ubi:tfkhdyt/geminicommit" = { version = "latest", exe = "gmc" }
claude = "latest"
