# Global tool versions managed by mise
[alias]
tpm = "https://github.com/svyatogor/asdf-tpm"

[settings]
# tools can read the versions files used by other version managers
# for example, .nvmrc in the case of node's nvm
idiomatic_version_file_enable_tools = ['node', 'ruby']

[tools]
node = "lts"
# ruby = "3"
# python = "3.12"
# go = "1.22"
fzf = "latest"
ripgrep = "latest"
jq = "latest"
neovim = "latest"
bat = "latest"
eza = "latest"
lazygit = "latest"
delta = "latest"
starship = "latest"
tpm = "latest"
zoxide = "latest"
"ubi:openai/codex" = { version = "latest", matching_regex = "(arm64|aarch64).*(linux|darwin).*(musl|static)", rename_exe = "codex" }
"ubi:tfkhdyt/geminicommit" = { version = "latest", exe = "gmc" }
claude = "latest"
