shell = "bash -c '{}'"
default-scheme = "base16-mocha"

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "tinted-fzf"
hook = ". %f"
themes-dir = "sh"

[[items]]
path = "https://github.com/tinted-theming/tinted-shell"
name = "tinted-shell"
themes-dir = "scripts"
hook = ". %f"

[[items]]
path = "https://github.com/tinted-theming/tinted-delta"
name = "tinted-delta"
themes-dir = "configs"
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-terminal"
path = "https://github.com/tinted-theming/tinted-terminal"
themes-dir = "themes/wezterm"
supported-systems = ["base16", "base24"]
hook = "mkdir -p ~/.local/share/wezterm/colors && cp -f %f ~/.local/share/wezterm/colors/tinted-theming.toml"
