[tools]
node = "24"
awscli = "latest"
aws-vault = "latest"
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
jq = "latest"
lazygit = "latest"
lazydocker = "latest"
opencode = "latest"
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
tmux = "latest"
worktrunk = "latest"
yazi = "latest"
zoxide = "latest"
neovim = "latest"
codex = "latest"
