[tools]
node = "24"
awscli = "latest"
aws-vault = "latest"
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
jq = "latest"
lazygit = "latest"
lazydocker = "latest"
opencode = "latest"
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
tmux = "latest"
worktrunk = "latest"
yazi = "latest"
zoxide = "latest"
neovim = "nightly"
codex = "latest"
"github:joshmedeski/sesh" = "latest"
markdownlint-cli2 = "latest"
claude = "latest"
"npm:typescript" = "7"
"npm:vscode-langservers-extracted" = "latest"
"npm:@tailwindcss/language-server" = "latest"
