add_newline = true
command_timeout = 200
format = "[$directory$aws$git_branch$git_status]($style)$character"
palette = "catppuccin_frappe"

[aws]
symbol = " "
[aws.region_aliases]
eu-central-1 = "eu"
eu-west-1 = "ie"
us-east-1 = "us"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
repo_root_style = "bold cyan"
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
symbol = " "
truncation_length = 16

[git_status]
ahead = "⇡${count} "
behind = "⇣${count} "
conflicted = " "
deleted = ""
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
format = "[$all_status]($style)"
modified = " "
renamed = ""
staged = ""
stashed = ""
style = "cyan"
untracked = ""
up_to_date = " "
