#!/usr/bin/env bash
#MISE description="Regenerate root Brewfile from current system"
set -euo pipefail

which brew >/dev/null 2>&1 || { echo "brew not found"; exit 1; }
brew bundle dump --force --describe --file=./Brewfile
